spring:
  profiles:
    active: local
  datasource:
    hikari:
      maxLifetime: 60000 # 连接的最大存活时间，单位为毫秒（10分钟）
      connection-test-query: SELECT 1 FROM DUAL# 用于测试连接是否有效的SQL查询
mybatis:
   mapperLocations: classpath:/mapper/*.xml
ollama:
  url: http://127.0.0.1:6006
comfy-ui:
  url: http://127.0.0.1:8188/api/
  view-url: http://127.0.0.1:8188/api/
  json-path: C:\\Users\\86186\\Desktop\\Comfy-UI.json
cloud:
  ip: 120.27.201.34
  file-path: /root/cloudFile/
  user: ftpUser
  password: 1qazxCDE#@
