CREATE TABLE IF NOT EXISTS DRAWPRO_BOARD (
  ID VARCHAR(64) NOT NULL PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  CURRENT_VERSION BIGINT NOT NULL DEFAULT 0,
  DATA_JSON LONGTEXT NOT NULL,
  CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
